# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest AS base

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Fr3ddy*123 
ENV MSSQL_PID=Express
ENV MSSQL_TCP_PORT=1433

# Expose the SQL Server port
EXPOSE 1433

# Copy the combined SQL script to the container
COPY NutritionSystem.Infrastructure/Migrations_scripts/migration_script.sql /scripts/migration_script.sql

# Start SQL Server and execute the migration script
CMD /opt/mssql/bin/sqlservr & sleep 45 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Fr3ddy*123 -C -i /scripts/migration_script.sql -o /tmp/sql_output.log & sleep infinity