networks:
    nurtricenter-net:
        driver: bridge
services:
  rabbitmq:
      image: rabbitmq:3.13.7-management
      container_name: rabbitmq
      ports:
        - "5672:5672"  # Puerto AMQP
        - "15672:15672" # UI de gestión
      volumes:
        - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
        RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
      networks:
        - nurtricenter-net #actualizar network
      